Lesson4
IKSANOVA/Python2 pull request #5
Opened 2021-10-30 20:52 UTC by IKSANOVA

2021-11-08 20:46 UTC, ketzhen requested changes
Обязательно поправь все проблемные места

2021-11-08 20:46 UTC, ketzhen commented on pages/blog_pages/main_pages.py
> +    def check_button_new(self):
Я бы переименовала в check_button_new_not_present - ты же внутри именно отсутствие проверяешь

2021-11-08 20:46 UTC, ketzhen commented on pages/blog_pages/post_modify_page.py
> +    def click_edit_button(self):
Этот метод, метод удаления и подтверждения удаления относятся к PostPage (таких кнопок нет на главной блога, только на странице поста)

2021-11-08 20:46 UTC, ketzhen commented on tests/tests_blog/test_post.py
> +
А куда фикстуру удаления поста потеряла?

2021-11-08 20:46 UTC, ketzhen commented on tests/tests_blog/test_post.py
> +class TestsBlogModify:
И тут тоже нужна фикстура удаления поста

2021-11-08 20:46 UTC, ketzhen commented on tests/tests_blog/test_post.py
> +
Тебе надо тут вызывать фикстуру создания поста, иначе что ты удаляешь?

2021-11-14 12:34 UTC, merged

2021-11-14 18:53 UTC, IKSANOVA commented on pages/blog_pages/main_pages.py
> +    def check_button_new(self):
+